# IF STATEMENTS

# 1. Average_grades

## a. Average_grades function

In [167]:
import random
import numpy as np
import math 
from collections import Counter

### a. *average_grades function*

In [168]:
def average_grades(stu_points):

    attendance_point, mid_point, final_point = stu_points

    # percent points
    attendance_percent = 0.2
    mid_percent = 0.2
    final_percent = 1 - (attendance_percent + mid_percent)

    x = attendance_percent * attendance_point + mid_percent * mid_point + final_percent * final_point
    average_grade = round(x,2)
    
    return average_grade

## b. generate students list points

In [169]:
def gen_float_list(number, lower_bound, upper_bound):
    float_list = []

    for i in range(number):
        value_ = random.uniform(lower_bound, upper_bound)
        value = round(value_, 2)
        float_list.append(value)
        
    return float_list

In [170]:
# generate_list_students_points
def gen_list_students_points(num_students, all_kinds_of_points, lower_bound, upper_bound):
    list_stu_points = []
    
    for __ in range(num_students):
        student_points = gen_float_list(all_kinds_of_points, lower_bound, upper_bound)
        list_stu_points.append(student_points)
         
    return list_stu_points

> check LETTER POINT (A+  A  B+  B  C+  C  D+  D  F)

In [171]:
def letter_point(student_point):
    if student_point < 4.0:
        letter_point = 'F'
    elif student_point < 5:
        letter_point = 'D'
    elif student_point < 6.5:
        letter_point = 'C'
    elif student_point < 8:
        letter_point = 'B'
    elif student_point < 9:
        letter_point = 'A'
    else:
        letter_point = 'A+'
    
    return letter_point

In [172]:
# create 20 student's points

num_students = 20
lower_score = 6
percent_lower_score = 50/100

stu_geq_lower_score = math.floor(num_students * percent_lower_score)

# attendance points and mid points 
stu_points = gen_list_students_points(num_students, 2, 0 ,10)

# final points
final_points = gen_float_list(stu_geq_lower_score, 6, 10) \
               + gen_float_list(num_students - stu_geq_lower_score, 0, 10)

for i in range(num_students):
    stu_points[i].append(final_points[i])

In [173]:
stu_average_points = []
stu_letter_points = []

for i in range(num_students):
    stu_point = stu_points[i]
    
    average_grade = average_grades(stu_point)
    stu_average_points.append(average_grade)

    letter = letter_point(average_grade)
    stu_letter_points.append(letter)


In [174]:
print("list points of students \n")
print("Index", "\t", "points", "\t\t",
        "average_points", "\t",
        "letter_points", "\n"
        )
for i in range(num_students):
    print(i+1, "\t", stu_points[i], "\t\t",
        stu_average_points[i], "\t\t",
        stu_letter_points[i], "\n"
        )

list points of students 

Index 	 points 		 average_points 	 letter_points 

1 	 [6.1, 1.5, 9.69] 		 7.33 		 B 

2 	 [7.13, 0.94, 6.98] 		 5.8 		 C 

3 	 [3.65, 5.14, 6.89] 		 5.89 		 C 

4 	 [9.87, 9.41, 7.1] 		 8.12 		 A 

5 	 [4.35, 7.8, 8.05] 		 7.26 		 B 

6 	 [7.65, 1.44, 9.96] 		 7.79 		 B 

7 	 [9.95, 6.83, 7.84] 		 8.06 		 A 

8 	 [1.76, 4.62, 8.07] 		 6.12 		 C 

9 	 [8.99, 7.98, 7.34] 		 7.8 		 B 

10 	 [8.62, 0.86, 9.84] 		 7.8 		 B 

11 	 [3.3, 9.77, 4.94] 		 5.58 		 C 

12 	 [7.76, 0.64, 4.62] 		 4.45 		 D 

13 	 [4.92, 9.78, 8.1] 		 7.8 		 B 

14 	 [4.33, 6.71, 7.53] 		 6.73 		 B 

15 	 [9.25, 0.97, 9.3] 		 7.62 		 B 

16 	 [1.87, 3.43, 1.94] 		 2.22 		 F 

17 	 [6.91, 2.28, 2.97] 		 3.62 		 F 

18 	 [4.7, 2.38, 7.89] 		 6.15 		 C 

19 	 [4.23, 2.01, 0.3] 		 1.43 		 F 

20 	 [0.53, 4.2, 6.53] 		 4.86 		 D 



## c. list of students has letter point greater or equal than B

In [175]:
stu_geqB_list = [] # list of students has letter point greater or equal than B
print("list of students has letter point greater or equal than B \n")
print("Index", "\t", "points", "\t", "letter points")
for i in range(num_students):
    if stu_letter_points[i] in ['B', 'A', 'A+']:
        stu_geqB_list.append([i, stu_points[i], stu_letter_points[i]])
        print(i+1, "\t", stu_points[i], "\t", stu_letter_points[i])

list of students has letter point greater or equal than B 

Index 	 points 	 letter points
1 	 [6.1, 1.5, 9.69] 	 B
4 	 [9.87, 9.41, 7.1] 	 A
5 	 [4.35, 7.8, 8.05] 	 B
6 	 [7.65, 1.44, 9.96] 	 B
7 	 [9.95, 6.83, 7.84] 	 A
9 	 [8.99, 7.98, 7.34] 	 B
10 	 [8.62, 0.86, 9.84] 	 B
13 	 [4.92, 9.78, 8.1] 	 B
14 	 [4.33, 6.71, 7.53] 	 B
15 	 [9.25, 0.97, 9.3] 	 B


# (Dictionaries) 1.

## read student name file

In [176]:
stu_name_list = []

with open('student_names.txt') as stu_name_file:
    lines = stu_name_file.readlines()

for line in lines:
    stu_name_list.append(line.strip())

student_point_list = list(zip(stu_name_list, stu_points,
                             stu_average_points, stu_letter_points))

## (Dictionaries) 1.1 --> 1.3

In [177]:
max_Aver_point = max(stu_average_points)
min_Aver_point = min(stu_average_points)

stu_max_point_list = []
stu_min_point_list = []
stu_B_point_list = []

for i in range(num_students):
    # max_Aver_point
    if stu_average_points[i] == max_Aver_point:
        stu_name = stu_name_list[i]
        stu_max_point_list.append(stu_name)
    # min_Aver_point
    if stu_average_points[i] == min_Aver_point:
        stu_name = stu_name_list[i]
        stu_min_point_list.append(stu_name)
    if stu_letter_points[i] == 'B':
        stu_name = stu_name_list[i]
        stu_B_point_list.append(stu_name)

print("List students has max average point is: \n", stu_max_point_list, max_Aver_point)
print("List students has min average point is: \n", stu_min_point_list, min_Aver_point)
print("List students has B letter point is: \n", stu_B_point_list)

List students has max average point is: 
 ['Nguyen Van A4'] 8.12
List students has min average point is: 
 ['Nguyen Van A19'] 1.43
List students has B letter point is: 
 ['Nguyen Van A1', 'Nguyen Van A5', 'Nguyen Van A6', 'Nguyen Van A9', 'Nguyen Van A10', 'Nguyen Van A13', 'Nguyen Van A14', 'Nguyen Van A15']


In [178]:
stu_name_aver_points_dict = dict(zip(stu_name_list, stu_average_points))
sorted_name_aver_point = sorted(stu_name_aver_points_dict, \
                                    key=lambda \
                                    stu_name : stu_name_aver_points_dict[stu_name], reverse = True) 

print("student and average point is")
for name, point in stu_name_aver_points_dict.items():
    print(name, "\t", point)


student and average point is
Nguyen Van A1 	 7.33
Nguyen Van A2 	 5.8
Nguyen Van A3 	 5.89
Nguyen Van A4 	 8.12
Nguyen Van A5 	 7.26
Nguyen Van A6 	 7.79
Nguyen Van A7 	 8.06
Nguyen Van A8 	 6.12
Nguyen Van A9 	 7.8
Nguyen Van A10 	 7.8
Nguyen Van A11 	 5.58
Nguyen Van A12 	 4.45
Nguyen Van A13 	 7.8
Nguyen Van A14 	 6.73
Nguyen Van A15 	 7.62
Nguyen Van A16 	 2.22
Nguyen Van A17 	 3.62
Nguyen Van A18 	 6.15
Nguyen Van A19 	 1.43
Nguyen Van A20 	 4.86


In [179]:
print("sorted student point:\n")
for i in range(num_students):
    stu_name = sorted_name_aver_point[i]
    print(stu_name,"\t", stu_name_aver_points_dict[stu_name])

sorted student point:

Nguyen Van A4 	 8.12
Nguyen Van A7 	 8.06
Nguyen Van A9 	 7.8
Nguyen Van A10 	 7.8
Nguyen Van A13 	 7.8
Nguyen Van A6 	 7.79
Nguyen Van A15 	 7.62
Nguyen Van A1 	 7.33
Nguyen Van A5 	 7.26
Nguyen Van A14 	 6.73
Nguyen Van A18 	 6.15
Nguyen Van A8 	 6.12
Nguyen Van A3 	 5.89
Nguyen Van A2 	 5.8
Nguyen Van A11 	 5.58
Nguyen Van A20 	 4.86
Nguyen Van A12 	 4.45
Nguyen Van A17 	 3.62
Nguyen Van A16 	 2.22
Nguyen Van A19 	 1.43


# 2. Tic - Tac - Toe

## tic-toc-toe

In [180]:
def create_tic_tac_toe(ttt_size):
    size_board = ttt_size**2 
    # first_player_steps 
    if ttt_size % 2 == 0:
        first_player_steps = size_board//2
    else:
        first_player_steps = size_board//2 + 1

    ttt_input_list_0 = [0]*first_player_steps + [1]*(size_board - first_player_steps)
    ttt_input_list_1 = [1]*first_player_steps + [0]*(size_board - first_player_steps)

    random.shuffle(ttt_input_list_0)
    random.shuffle(ttt_input_list_1)

    matrix_0 = []
    while ttt_input_list_0 != []:
        matrix_0.append(ttt_input_list_0[:ttt_size])
        ttt_input_list_0 = ttt_input_list_0[ttt_size:]

    matrix_1 = []
    while ttt_input_list_1 != []:
        matrix_1.append(ttt_input_list_1[:ttt_size])
        ttt_input_list_1 = ttt_input_list_1[ttt_size:]
        
    option = random.randint(0,1) 
    if option == 0:
        return matrix_0
    else:
        return matrix_1

In [181]:
from collections import Counter
import numpy as np

def tic_tac_toe(ttt_size):
    ttt_input = np.array(create_tic_tac_toe(ttt_size))
    print(ttt_input)

    nRows = [row.tolist() for row in ttt_input]
    nCols = [row.tolist() for row in ttt_input.transpose()]
    nDiagonals = [
                [ttt_input[i][i] 
                for i in range(ttt_size)] 
                , 
                [ttt_input[i][ttt_size - 1 - i] 
                for i in range(ttt_size)]
                ]
    
    nAll_kinds_of_ttt = nRows + nCols + nDiagonals
    
    winner_conditions = [
                        [0 for _ in range(ttt_size)]
                        , 
                        [1 for _ in range(ttt_size)]
                        ]

    # first player
    res = dict(sum(map(Counter, ttt_input), Counter()))
    
    if res[0] > res[1]:
        first_player = 0
        if winner_conditions[0] in nAll_kinds_of_ttt:
            winner = 0
            return print("player[0] win!")
    
    if res[1] > res[0]:
        first_player = 1
        if winner_conditions[1] in nAll_kinds_of_ttt:
            winner = 1
            return print("player[1] win!")

    if (winner_conditions[0] not in nAll_kinds_of_ttt) \
        and \
        (winner_conditions[1] not in nAll_kinds_of_ttt):
        return print("Draw!")
    

In [166]:
tic_tac_toe(5)

[[1 0 0 1 1]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [1 0 0 1 0]
 [0 0 1 1 1]]
Draw!
