# IF STATEMENTS

# 1. Average_grades

## a. Average_grades function

In [894]:
import random
import numpy as np
import math 
from collections import Counter

In [942]:
def generate_float_list(float_list_size, decimal_digits = 1, lower_bound_point = 0, upper_bound_point = 10):
    # Generate a float numbers list 
    # 0*100->10*100/10^2 

    # 6 <=
    # float_list = []
    # up_range = 10**(decimal_digits)
    # for __ in range(float_list_size):
    #     value = random.randint(lower_bound_point, 10*up_range)/up_range
    #     float_list.append(value)
    # return(float_list)

    # float_list = []
    # for i in range(float_list_size):
    #     x = random.uniform(lower_bound_point, upper_bound_point)
    #     float_list.append(round(x,decimal_digits))

    float_list = [round(random.uniform(lower_bound_point, upper_bound_point),decimal_digits)  
                    for i in range(float_list_size)]
    
    return float_list


In [943]:
generate_float_list(10,2,12,100)

[32.03, 38.1, 88.56, 35.37, 57.98, 21.85, 60.8, 76.79, 16.01, 45.92]

In [897]:
generate_float_list(4,2)

[8.9, 2.06, 9.91, 6.28]

In [898]:
# generate_list_students_points
def generate_list_students_points(num_students, all_kinds_of_points = 3):
    list_students_points = []
    for __ in range(num_students):
        student_points = generate_float_list(all_kinds_of_points)
        list_students_points.append(student_points)
    return(list_students_points)

### a. *average_grades function*

In [949]:
def average_grades(student_points):

    # student_points have attendance_point, mid_point, final_point
    attendance_point, mid_point, final_point = student_points

    # percent points
    attendance_percent = 0.2
    mid_percent = 0.2
    final_percent = 1 - (attendance_percent + mid_percent)

    x = attendance_percent * attendance_point + mid_percent * mid_point + final_percent * final_point
    average_grade = round(x,2)
    return average_grade

In [951]:
student1_points = generate_float_list(3)
print(student1_points)
print(average_grades(student1_points))

student2_points = [7,8,9]
print(student2_points)
print(average_grades(student2_points))

print(average_grades([10,9,9]))


[6.8, 2.6, 0.5]
2.18
[7, 8, 9]
8.4
9.2


### b. generate students list points

In [901]:
def generate_float_list(float_list_size, decimal_digits = 1, lower_bound_point = 0):
    # Generate a float numbers list 
    float_list = []
    up_range = 10**(decimal_digits)
    for __ in range(float_list_size):
        value = random.randint(lower_bound_point*up_range, 10*up_range)/up_range
        float_list.append(value)
    return(float_list)

In [902]:
generate_float_list(3,1,6)

[8.2, 8.6, 9.4]

In [903]:
# generate_list_students_points
def generate_list_students_points(num_students, all_kinds_of_points = 3,lower_bound_points =0):
    list_students_points = []
    decimal_digits = 1
    for __ in range(num_students):
        student_points = generate_float_list(all_kinds_of_points,decimal_digits,lower_bound_points)
        list_students_points.append(student_points)
        
    return list_students_points

In [904]:
# ví dụ : Tạo một list chứa 20 phần tử, mỗi phần tử gồm 3 thành phần, các thành phần >=6
generate_list_students_points(20,3,6)

[[9.3, 6.2, 9.7],
 [7.0, 6.3, 9.8],
 [10.0, 9.0, 8.8],
 [6.4, 6.7, 9.9],
 [8.2, 7.1, 6.6],
 [9.0, 8.5, 8.2],
 [8.3, 9.6, 8.6],
 [9.2, 8.2, 9.8],
 [7.1, 9.5, 7.6],
 [8.0, 8.9, 9.5],
 [9.5, 8.9, 7.8],
 [10.0, 9.0, 8.2],
 [6.8, 6.0, 8.7],
 [6.0, 7.4, 7.1],
 [7.5, 7.0, 6.8],
 [9.7, 6.7, 7.1],
 [8.7, 8.1, 8.4],
 [6.7, 6.9, 9.9],
 [9.0, 6.3, 6.4],
 [6.1, 8.0, 8.0]]

In [905]:
# Ví dụ : Tạo một list chứa 20 phần tử, mỗi phần tử gồm 1 thành phần, các thành phần >=6
generate_list_students_points(20,1,6)

[[8.5],
 [8.4],
 [7.0],
 [8.8],
 [7.9],
 [9.0],
 [9.4],
 [9.2],
 [9.6],
 [7.7],
 [9.4],
 [9.3],
 [8.6],
 [9.7],
 [6.8],
 [9.2],
 [8.1],
 [9.3],
 [10.0],
 [6.8]]

In [906]:
def generate_list_students_points_custom(num_students,  all_kinds_of_points = 3, percent_students = 0.5,lower_bound_point = 6):
    # list_students_points_custom = []
    
    # list_students_points_custom = generate_list_students_points(num_students,2)

    students_geq_lower_bound_point = int(num_students/2 + 1)
    
    list_points_geq_lower_bound_point = generate_list_students_points(students_geq_lower_bound_point, all_kinds_of_points, lower_bound_point)

    list_students_points_rest = generate_list_students_points(num_students - students_geq_lower_bound_point ,all_kinds_of_points, 0)

    list_students_points_custom = list_points_geq_lower_bound_point + list_students_points_rest

    return list_students_points_custom

In [907]:
# tạo một list gồm điểm của 20 sinh viên, mỗi phần tử gồm 3 đầu điểm, có trên 50% số sinh viên có điểm thành phần lớn hơn 6
nums_students = 20
students_points_list = generate_list_students_points_custom(nums_students, 3, 0.5, 6)

# + tính điểm trung bình của 20 sinh viên trên
print("index \t points \t average_grades")
for index, student_point in enumerate(students_points_list):
    print(index + 1, " \t",student_point," \t", average_grades(student_point))
    

index 	 points 	 average_grades
1  	 [7.4, 7.0, 8.5]  	 7.98
2  	 [9.1, 6.4, 6.5]  	 7.0
3  	 [9.5, 7.6, 8.2]  	 8.34
4  	 [9.4, 6.2, 8.2]  	 8.04
5  	 [7.7, 7.1, 8.0]  	 7.76
6  	 [9.5, 8.2, 9.6]  	 9.3
7  	 [7.4, 8.3, 8.5]  	 8.24
8  	 [7.4, 8.5, 9.3]  	 8.76
9  	 [6.6, 6.5, 7.8]  	 7.3
10  	 [6.5, 6.2, 7.5]  	 7.04
11  	 [6.5, 6.2, 8.1]  	 7.4
12  	 [4.3, 6.2, 8.0]  	 6.9
13  	 [3.0, 2.2, 8.9]  	 6.38
14  	 [5.0, 7.2, 5.9]  	 5.98
15  	 [1.8, 2.9, 2.1]  	 2.2
16  	 [6.2, 0.4, 1.5]  	 2.22
17  	 [5.4, 5.2, 9.0]  	 7.52
18  	 [4.6, 7.6, 7.8]  	 7.12
19  	 [9.8, 6.8, 9.9]  	 9.26
20  	 [8.4, 2.1, 4.0]  	 4.5


> check LETTER POINT (A+  A  B+  B  C+  C  D+  D  F)

In [908]:
def letter_point(student_point):
    if student_point < 4.0:
        letter_point = 'F'
    elif student_point < 5:
        letter_point = 'D'
    elif student_point < 6.5:
        letter_point = 'C'
    elif student_point < 8:
        letter_point = 'B'
    elif student_point < 9:
        letter_point = 'A'
    else:
        letter_point = 'A+'
    
    return letter_point

        

In [909]:
nums_students = 20
students_points_list = generate_list_students_points_custom(nums_students, 3, 0.5, 6)

student_geq_B = []
for index, student_point in enumerate(students_points_list):
    value = average_grades(student_point)
    if value > 8:
        student_geq_B.append(letter_point(value))
        print(index + 1,"\t",student_point,"\t",average_grades(student_point),"\t", letter_point(value))


1 	 [8.0, 10.0, 7.9] 	 8.34 	 A
3 	 [8.9, 9.0, 9.2] 	 9.1 	 A+
4 	 [9.5, 10.0, 8.2] 	 8.82 	 A
5 	 [8.1, 9.3, 7.6] 	 8.04 	 A
6 	 [8.0, 9.9, 8.6] 	 8.74 	 A
7 	 [9.4, 9.8, 8.1] 	 8.7 	 A


# 2. Tic - Tac - Toe

In [910]:
# test
#tic_tac_toe_input
ttt_input = [value % 2 for value in random.sample(range(100,1000),9)]
print(ttt_input)

[0, 0, 1, 0, 1, 0, 0, 0, 0]


In [911]:
import numpy as np
# 2
nRows = 3
nCols = 3
tic_tac_toe_board = np.random.randint(2, size=(nRows, nCols))

print(tic_tac_toe_board)

[[0 0 1]
 [0 0 0]
 [1 0 0]]


In [912]:
## test code
tic_tac_toe_size_board = 3
tic_tac_toe_input = np.random.randint(2, size=(tic_tac_toe_size_board, tic_tac_toe_size_board))

print("tic_tac_toe_board \n",tic_tac_toe_input)

nRows = [row.tolist() for row in tic_tac_toe_input]
nCols = [row.tolist() for row in tic_tac_toe_input.transpose()]

print("nRows:", nRows)

print("nCols: ", nCols)
# nDiagonals = [[tic_tac_toe_input[i][i] for i in range(tic_tac_toe_size_board)],[tic_tac_toe_input[i][tic_tac_toe_size_board - 1- i] for i in range(tic_tac_toe_size_board)]]
nDiagonals = [
                [tic_tac_toe_input[i][i] for i in range(tic_tac_toe_size_board)] 
                ,
                [tic_tac_toe_input[i][tic_tac_toe_size_board -1-i] for i in range(tic_tac_toe_size_board)]
                ]
print("nDiagonals: ",nDiagonals)

nAll_kinds_of_tic_tac_toe = nRows + nCols + nDiagonals

winner_conditions = [[0,0,0], [1,1,1]] 

print(winner_conditions[0], winner_conditions[1])

print("nAll_kinds_of_tic_tac_toe",nAll_kinds_of_tic_tac_toe)

res = dict(sum(map(Counter, tic_tac_toe_input), Counter()))

# print(str(res))
print(res[0], res[1])

print(max(res.values()))

tic_tac_toe_board 
 [[1 1 1]
 [0 0 0]
 [0 1 0]]
nRows: [[1, 1, 1], [0, 0, 0], [0, 1, 0]]
nCols:  [[1, 0, 0], [1, 0, 1], [1, 0, 0]]
nDiagonals:  [[1, 0, 0], [1, 0, 0]]
[0, 0, 0] [1, 1, 1]
nAll_kinds_of_tic_tac_toe [[1, 1, 1], [0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 0, 1], [1, 0, 0], [1, 0, 0], [1, 0, 0]]
5 4
5


In [913]:
# test
def convert_ttt_input_to_matrix(maxtrix_size = 3):
    n = maxtrix_size**2
    first = int(n/2+1)
    ttt_input_list_0 = [0]*first + [1]*(n-first)
    ttt_input_list_1 = [1]*first + [0]*(n-first)
    for i in [0,1]:
        matrix = []
        while ttt_input_list_0 != []:
            matrix.append(ttt_input_list_0[:maxtrix_size])
            ttt_input_list_0 = ttt_input_list_0[maxtrix_size:]
    return matrix

In [914]:
convert_ttt_input_to_matrix(3)

[]

## tic-toc-toe

In [915]:
def create_input_tic_tac_toe(tic_tac_toe_size_board=3):
    n = tic_tac_toe_size_board**2
    first_steps = int(n/2 + 1)

    ttt_input_list_0 = [0]*first_steps+ [1]*(n-first_steps)
    ttt_input_list_1 = [1]*first_steps+ [0]*(n-first_steps)

    random.shuffle(ttt_input_list_0)
    random.shuffle(ttt_input_list_1)

    first_0 = ttt_input_list_0
    first_1 = ttt_input_list_1

    matrix_0 = []
    while ttt_input_list_0 != []:
        matrix_0.append(ttt_input_list_0[:tic_tac_toe_size_board])
        ttt_input_list_0 = ttt_input_list_0[tic_tac_toe_size_board:]

    matrix_1 = []
    while ttt_input_list_1 != []:
        matrix_1.append(ttt_input_list_1[:tic_tac_toe_size_board])
        ttt_input_list_1 = ttt_input_list_1[tic_tac_toe_size_board:]
    option = random.randint(0,1) 
    if option == 0:
        return matrix_0
    else:
        return matrix_1

In [916]:
from collections import Counter
import numpy as np

def tic_tac_toe(tic_tac_toe_size_board = 3):
    # tic_tac_toe_input = np.random.randint(2, size=(tic_tac_toe_size_board, tic_tac_toe_size_board))
    tic_tac_toe_input = np.array(create_input_tic_tac_toe(tic_tac_toe_size_board))
    print(tic_tac_toe_input)
    nRows = [row.tolist() for row in tic_tac_toe_input]
    nCols = [row.tolist() for row in tic_tac_toe_input.transpose()]

    nDiagonals = [
                [tic_tac_toe_input[i][i] for i in range(tic_tac_toe_size_board)] 
                , 
                [tic_tac_toe_input[i][tic_tac_toe_size_board - 1 - i] for i in range(tic_tac_toe_size_board)]
                ]
    
    nAll_kinds_of_tic_tac_toe = nRows + nCols + nDiagonals
    
    winner_conditions = [
                        [0 for _ in range(tic_tac_toe_size_board)]
                        , 
                        [1 for _ in range(tic_tac_toe_size_board)]
                        ]

    # first player
    res = dict(sum(map(Counter, tic_tac_toe_input), Counter()))
    if res[0] > res[1]:
        first_player = 0
        if winner_conditions[0] in nAll_kinds_of_tic_tac_toe:
            winner = 0
            return print("player[0] win!")
    
    if res[1] > res[0]:
        first_player = 1
        if winner_conditions[1] in nAll_kinds_of_tic_tac_toe:
            winner = 1
            return print("player[1] win!")
    if (winner_conditions[0] not in nAll_kinds_of_tic_tac_toe) and (winner_conditions[1] not in nAll_kinds_of_tic_tac_toe):
        return print("Draw!")
    

In [921]:
tic_tac_toe(5)

[[1 0 0 1 0]
 [0 1 0 0 1]
 [0 1 1 0 0]
 [1 1 0 0 1]
 [1 1 1 0 1]]
Draw!


In [922]:
tic_tac_toe(4)

[[0 1 0 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 1 0]]
player[0] win!


In [924]:
tic_tac_toe()

[[1 1 0]
 [1 1 1]
 [0 0 0]]
player[1] win!


# 4. a-->f 